# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- script: json build --configuration $(buildConfiguration)
  displayname: 'json build $(buildConfiguration)'
  inputs:
    command: publish
    publishwebprojects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.Artifactstaging)
  zipafterPublish: True

- task:PublishBuildArtifact@1
  displayname: 'publish artifacts'